name: Auto Release on PR Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  calculate-version:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'auto-update-bgfx'
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.calc.outputs.new_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # needed to get tags
          
      - name: Calculate new version
        id: calc
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 || echo "v1.0.0")
          MAJOR=$(echo $LATEST_TAG | cut -d. -f1)
          MINOR=$(echo $LATEST_TAG | cut -d. -f2)
          PATCH=$(echo $LATEST_TAG | cut -d. -f3)
          NEW_TAG="${MAJOR}.${MINOR}.$((PATCH + 1))"
          echo "new_version=$NEW_TAG" >> $GITHUB_OUTPUT
          
  create-release:
    needs: calculate-version
    permissions:
      contents: write
    uses: ./.github/workflows/create-release.yml
    with:
      version: ${{ needs.calculate-version.outputs.new_version }}
    secrets: inherit
