name: Update Major Tag

on:
  release:
    types: [published]

jobs:
  update-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      
      - name: Update major tag
        run: |
          MAJOR_VERSION=$(echo ${{ github.event.release.tag_name }} | grep -o 'v[0-9]*')
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -fa $MAJOR_VERSION -m "Update $MAJOR_VERSION tag"
          git push origin $MAJOR_VERSION --force
